### PR TITLE
2.5-3.1x speedup on map generation, fixed memory leaks of plates arra…

### PR DESCRIPTION
**Pull request by cycloverid**
…y, fixed a divide-by-zero bug that was causing invalid masses

### CODE REVIEW

**Comment by ftomassetti** [comment]
Build passing on both AppVeyor and Travis. Matthew also told me that it is further improved the speedup (up to 6x!).

Things to do:
* check formatting
* add Matthew Kenneally among the contributors, with a link to his github profile
* bump vesion number (1.3.2? 1.4.0?)

@psi29a how we should do that? Should we copy his branch in a branch on the original project and then work on it there?

**Comment by psi29a** [comment]
Honestly, linthub does a good job looking at style.  We should enforce this in the future.

For me, it is the use of tabs instead of spaces (4). This is something I can fix after the fact which has nothing to do with the substance here. This isn't even exclusive to the patch. :)

As for the rest, please go ahead.  :)

**Comment by cycloverid** [comment]
I absolutely must read up on this now, I didn't even know this was a thing... a lot of people prefer spaces to tabs for indentation?

**Comment by ftomassetti** [comment]
@psi29a so should we merge it and fix the style later?

**Comment by psi29a** [comment]
absolutely :)

**Comment by ftomassetti** [comment]
Ok then, let's merge this one!

**Pull request merged**
